keys:
  # Decommissioned — kept for reference
  - &mab age1qu9d09aaf6gwhql7y2yhvzpu6k4vmearetjkwulryxza8cp9e5aszslp7g
  - &raphael age10uytscks5w3kxew8d83a68eylfa92lmkg4x0gq7efvgpzmxmeuwq8nat96
  - &uriel age1eljuw0nsq77tjg2vgmknvqu7pvl6t9qfucuyhtg5wf33s67nl92qxc4uug
  - &jehoel age1xvwcxn65xjrr9u37hy2mc2hkhvprnl6exuhtlyayg9d5083mt5ksrm4w9y
  - &caliban age1yc0zta2lenw96ll7t2fze97agp330xmf4tcphr4rguvtelz8854q49pt30

creation_rules:
  - path_regex: ^modules/features/supersecrets\.yaml$
    key_groups:
      - age:
          - *jehoel
          - *raphael
  - path_regex: ^modules/features/secrets\.yaml$
    key_groups:
      - age:
          - *uriel
          - *jehoel
          - *raphael
