theme = "nord"

[editor]
auto-format = true
bufferline = "multiple"
line-number = "relative"
text-width = 80

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
git-ignore = true
hidden = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[keys.normal]
A-x = ["extend_to_line_bounds"]
C-6 = ["increment"]
X = ["extend_line_above"]
C-y = [
    ":sh rm -f /tmp/unique-file",
    ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file',
    ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
    ":open %sh{cat /tmp/unique-file}",
    ":redraw",
]

[keys.normal.z]
w = "@v%zz"
x = "@vxzz"
z = "@mipvzz"

[keys.select]
A-x = ["extend_to_line_bounds"]
X = ["extend_line_above"]

[keys.select.z]
z = [
    ":sh zellij action toggle-floating-panes",
    ":pipe-to sh -c 'zellij action write-chars \"$(cat)\\n\"'",
    "normal_mode",
]
